

import 'package:ppv_components/features/expense/model/expense_model.dart';

final List<GreenNote> dummyGreenNotes = [
  GreenNote(
    sNo: "1",
    projectName: "Corporate Office Delhi",
    vendorName: "National Highways Invit Project Managers Private Limited",
    invoiceValue: "5575500.00",
    date: "11/09/2025 09:10 PM",
    status: "Sent for Approval",
    nextApprover: "Naveen Kumar",
  ),
  GreenNote(
    sNo: "2",
    projectName: "Kothakota Bypass – Kurnool",
    vendorName: "Surya Cartridge Solution - C Surya Babu",
    invoiceValue: "4750.00",
    date: "11/09/2025 08:30 PM",
    status: "Sent for Approval",
    nextApprover: "Dammavalam Sreedhar",
  ),
  GreenNote(
    sNo: "3",
    projectName: "Borekhedi Wadner",
    vendorName: "Lane Logic Consultants",
    invoiceValue: "207900.00",
    date: "11/09/2025 08:13 PM",
    status: "Sent for Approval",
    nextApprover: "Priyabrata Ghosh",
  ),
  GreenNote(
    sNo: "4",
    projectName: "Chittorgarh – Kota",
    vendorName: "Ajmer Vidyut Vitran Nigam Ltd. - Aroli",
    invoiceValue: "136563.00",
    date: "11/09/2025 06:01 PM",
    status: "Sent for Approval",
    nextApprover: "Naveen Kumar",
  ),
  GreenNote(
    sNo: "5",
    projectName: "Agra By pass",
    vendorName: "Elsamex Maintenance Services Limited",
    invoiceValue: "3150076.00",
    date: "11/09/2025 05:59 PM",
    status: "Sent for Approval",
    nextApprover: "Priyabrata Ghosh",
  ),
  GreenNote(
    sNo: "6",
    projectName: "Agra By pass",
    vendorName: "Gulshan Enterprises - Saddam Hussain",
    invoiceValue: "543061.00",
    date: "11/09/2025 05:58 PM",
    status: "Sent for Approval",
    nextApprover: "Priyabrata Ghosh",
  ),
  GreenNote(
    sNo: "7",
    projectName: "Nagpur Flyover",
    vendorName: "Shiv Construction Pvt Ltd",
    invoiceValue: "2500000.00",
    date: "10/09/2025 04:45 PM",
    status: "Sent for Approval",
    nextApprover: "Rohit Sharma",
  ),
  GreenNote(
    sNo: "8",
    projectName: "Bangalore Metro Phase II",
    vendorName: "Urban Infra Solutions",
    invoiceValue: "4923500.00",
    date: "10/09/2025 03:20 PM",
    status: "Sent for Approval",
    nextApprover: "Ankita Verma",
  ),
  GreenNote(
    sNo: "9",
    projectName: "Mumbai Coastal Road",
    vendorName: "Coastal Constructions LLP",
    invoiceValue: "8750000.00",
    date: "09/09/2025 01:15 PM",
    status: "Sent for Approval",
    nextApprover: "Vikram Patil",
  ),
  GreenNote(
    sNo: "10",
    projectName: "Delhi Metro Extension",
    vendorName: "Metro Builders & Developers",
    invoiceValue: "7654300.00",
    date: "09/09/2025 11:50 AM",
    status: "Sent for Approval",
    nextApprover: "Sonal Mehta",
  ),
];
